package org.greenmercury.speat;

/**
 * A class implementing this interface supplies events, and needs a handler to process these events.
 */
public interface EventSupplier<Api> {

  /**
   * Set the handler that accepts the events generated by this supplier.
   * @param handler
   */
  public void setHandler(Api handler) throws ConfigurationException, PipelineException;

  /**
   * Get the handler that accepts the events generated by this supplier.
   * @return the handler, or {@code null} if it has not been set
   */
  public Api getHandler();

  /**
   * Determine if this supplier has a API event handler for the events that it generates.
   * @return whether the handler has been set
   */
  public default boolean hasHandler() {
    return getHandler() != null;
  }

}
